name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - run: ls
      - run: rm package-lock.json

      - name: Install and Build
        run: |
          sudo apt-get update
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          source ~/.bashrc
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm install --lts
          nvm use --lts
          npm install
          npm run build
          cd .next
          pwd

      - name: Copy Build to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./.next/*" # Change this if your build output is in a different directory
          target: ${{ secrets.PATH }}
          rm: true

      # - name: SSH into Server and Deploy
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       pm2 stop your-app-name || true
      #       rm -rf /path/to/old/build
      #       mv /path/to/remote/directory /path/to/old/build
      #       mv /path/to/new/build /path/to/remote/directory
      #       pm2 start your-app-name
