name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - run: ls
      - run: rm package-lock.json

      - name: Install and Build
        run: |
          sudo apt-get update
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          source ~/.bashrc
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm install --lts
          nvm use --lts
          echo "NEXT_PUBLIC_BACKEND_ENDPOINT=${{ secrets.BACKEND_ENDPOINT }}" > .env
          npm install
          npm run build

      - name: SSH into Server and Stop server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            pm2 stop nustutor-frontend
            pm2 del nustutor-frontend

      - name: Copy Build to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "." # Change this if your build output is in a different directory
          target: ${{ secrets.PATH }}
          rm: true

      - name: SSH into Server and Run
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            pm2 start npm --name nustutor-frontend -- run start -- -p 3000
